<?php
	define('_ZNKLINK1', 'Sato(na)');
	define('_ZNKLINK2', 'Automatically from specific keyword inside the article link is stretched to the setting page. Compilation ahead keyword and link does in the management page.');
	define('_ZNKLINK3', 'You verify up-to-date version?');
	define('_ZNKLINK4', 'Exclusion [burogu]. In case of plural, please divide with the comma. Example');
	define('_ZNKLINK5', 'Link mode');
	define('_ZNKLINK6', 'It links to everything');
	define('_ZNKLINK7', 'It links to just the first 1 times');
	define('_ZNKLINK8', 'Is plug in setting put out to the item contribution picture?');
	define('_ZNKLINK9', 'Is link to the management page, indicated in the quick menu?');
	define('_ZNKLINK10', 'At the time of un installation, is the data cancelled?');
	define('_ZNKLINK11', 'To keyword link register picture');
	define('_ZNKLINK12', 'Keyword link');
	define('_ZNKLINK13', 'Link mode:');
	define('_ZNKLINK14', 'Setting of plug in option');
	define('_ZNKLINK15', 'It does not link');
	define('_ZNKLINK16', 'Upgrade of the table from old version completed.');
	define('_ZNKLINK17', 'It failed, in upgrade of the table from old version.');
	define('_ZNKLINK18', 'Keyword summary');
	define('_ZNKLINK19', 'Keyword');
	define('_ZNKLINK20', 'Ahead linking');
	define('_ZNKLINK21', 'Window');
	define('_ZNKLINK22', 'Ranking');
	define('_ZNKLINK23', 'Action');
	define('_ZNKLINK24', 'By your');
	define('_ZNKLINK25', 'Another window');
	define('_ZNKLINK26', 'Adding keyword');
	define('_ZNKLINK27', 'Target window');
	define('_ZNKLINK28', 'Another window is not opened');
	define('_ZNKLINK29', 'Another window is opened');
	define('_ZNKLINK30', 'Compilation');
	define('_ZNKLINK31', 'Addition');
	define('_ZNKLINK32', 'Keyword compilation');
	define('_ZNKLINK33', 'Compilation');
	define('_ZNKLINK34', 'Decision');
	define('_ZNKLINK35', 'The keyword which it appoints is not found.');
	define('_ZNKLINK36', 'It added.');
	define('_ZNKLINK37', 'It could not add.');
	define('_ZNKLINK38', 'It modified.');
	define('_ZNKLINK39', 'It could not modify.');
	define('_ZNKLINK40', 'It deleted.');
	define('_ZNKLINK41', 'It could not delete.');
?>